version: '3.5'

services:
  nginx-reverse-proxy:
    container_name: docker-compose-nginx-reverse-proxy
    image: nginx:1.21.1-alpine
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    ports:
      - "8081:80"
    restart: unless-stopped

  nginx-forward-proxy:
    container_name: docker-compose-nginx-forward-proxy
    build: ./forward_proxy
    environment:
      - NGINX_PORT=80
    ports:
      - "8082:80"
    restart: unless-stopped

  nginx-forward-proxy-tyson:
    container_name: docker-compose-nginx-forward-proxy-tyson
    build: ./forward_proxy_tyson
    environment:
      - NGINX_PORT=80
    ports:
      - "5555:80"
    restart: unless-stopped